---
- hosts: 172.31.47.147 
  become: yes
  tasks: 
  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt:
       name: tree
       stateeee: present
    ignore_errors: True

  - name: install wget
    apt:
      name: wget
      state: present
