---
- hosts: 172.31.47.147 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy a file into  ansible node side
    copy:
      src: mystaticfile.txt
      dest: /home/ubuntu/mystaticfile
    notify: restartwebserver

  - name: copy index file into ansible node side
    template:
        src:  myindex.j2
        dest: /var/www/html/index.html
    notify: 
     - restartwebserver

  - name: download internet file
    get_url:
       url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
       dest: /home/ubuntu/jenkins.war
       force_basic_auth: yes

  - name: create a folder
    file:
      path: /home/ubuntu/myfoder
      state: directory
      
  handlers:  
  - name: restartwebserver
    service:
       name: apache2
       state: restarted